"""
Q9 Find the Difference

You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

Examples

find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"

"""

def find_the_difference(s, t):
    if(len(t)>len(s)):
        lst1 = []
        for l in s:
            lst1.append(l)
        for letter in t:
            if (letter not in lst1):
                return letter
            else:
                lst1.remove(letter)
            
    else:
        lst1 = []
        for l in t:
            lst1.append(l)
        for letter in s:
            if (letter not in lst1):
                return letter
            else:
                lst1.remove(letter)